In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

!mkdir -p '/content/gdrive/My Drive/colab-materials-data8-notebooks/'
!git clone https://github.com/data-8/materials-sp22-colab '/content/gdrive/My Drive/colab-materials-data8-notebooks/materials-sp22-colab/'

%pip install otter-grader==4.4.1
%cd /content/gdrive/MyDrive/colab-materials-data8-notebooks/materials-sp22-colab//

from datascience import *
import numpy as np

## Columns of Tables are Arrays ##

In [2]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

In [3]:
nba.num_rows

528

In [4]:
nba.num_columns

5

In [5]:
nba.labels

('rank', 'name', 'position', 'team', 'salary')

In [6]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

In [7]:
warriors.relabeled('salary', '$')

rank | name                | position | team                  | $
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000
60   | Draymond Green      | PF       | Golden State Warriors | 18539130
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310
497  | Eric Paschall       | PF       | Golden State Warriors | 898310
502  | Damion Lee          | SG       | Golden State Warriors | 842327
... (3 rows omitted)

In [8]:
warriors

rank | name                | position | team                  | salary
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000
60   | Draymond Green      | PF       | Golden State Warriors | 18539130
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310
497  | Eric Paschall       | PF       | Golden State Warriors | 898310
502  | Damion Lee          | SG       | Golden State Warriors | 842327
... (3 rows omitted)

In [10]:
warriors = (
    nba.where('team', 'Golden State Warriors')
    .drop('team')
    .relabeled('salary', '$'))
warriors.show(3)

In [13]:
warriors.select('$')

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327
... (3 rows omitted)

In [14]:
type(warriors.select('$'))

datascience.tables.Table

In [15]:
warriors.column('$')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,
         350189])

In [16]:
type(warriors.column('$'))

numpy.ndarray

In [17]:
np.sum(warriors.column('$'))

106010951

In [25]:
np.max(warriors.column('$'))

40231758

In [20]:
warriors.column('$').item(0)

40231758

In [23]:
warriors.show(warriors.num_rows)

In [24]:
np.abs(warriors.column('$'))

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,
         350189])

In [27]:
warriors.select('name', '$')

name                | $
Stephen Curry       | 40231758
Klay Thompson       | 32742000
Draymond Green      | 18539130
Kevon Looney        | 4464226
Willie Cauley-Stein | 2177483
Jordan Poole        | 1964760
Omari Spellman      | 1897800
Alen Smailagic      | 898310
Eric Paschall       | 898310
Damion Lee          | 842327
... (3 rows omitted)

In [28]:
np.average(warriors.column('$'))

8154688.538461538

In [29]:
suns = (
    nba.where('team', 'Phoenix Suns')
    .drop('team')
    .relabeled('salary', '$'))
suns.show(3)

In [30]:
np.average(suns.column('$'))

5761373.947368421

In [31]:
np.sum(warriors.column('$')) - np.sum(suns.column('$'))

-3455154

In [32]:
warriors.num_rows

13

In [33]:
suns.num_rows

19

## Ranges ##

In [34]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [37]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [46]:
warriors.take(0, 1, 2, 3, 4)

rank | name                | position | $
1    | Stephen Curry       | PG       | 40231758
13   | Klay Thompson       | SG       | 32742000
60   | Draymond Green      | PF       | 18539130
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483

In [48]:
warriors.take(np.arange(5))

rank | name                | position | $
1    | Stephen Curry       | PG       | 40231758
13   | Klay Thompson       | SG       | 32742000
60   | Draymond Green      | PF       | 18539130
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483

In [49]:
warriors.take(np.arange(5, 10))

rank | name           | position | $
332  | Jordan Poole   | SG       | 1964760
339  | Omari Spellman | PF       | 1897800
496  | Alen Smailagic | PF       | 898310
497  | Eric Paschall  | PF       | 898310
502  | Damion Lee     | SG       | 842327

In [50]:
np.sum(warriors.take(np.arange(5)).column('$'))

98154597

In [54]:
np.sum(suns.take(np.arange(5)).column('$'))

76137832

In [55]:
warriors.take(3, 4)

rank | name                | position | $
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483

In [56]:
warriors.select('name', 'position')

name                | position
Stephen Curry       | PG
Klay Thompson       | SG
Draymond Green      | PF
Kevon Looney        | PF
Willie Cauley-Stein | C
Jordan Poole        | SG
Omari Spellman      | PF
Alen Smailagic      | PF
Eric Paschall       | PF
Damion Lee          | SG
... (3 rows omitted)

In [57]:
warriors.select(1, 2)

name                | position
Stephen Curry       | PG
Klay Thompson       | SG
Draymond Green      | PF
Kevon Looney        | PF
Willie Cauley-Stein | C
Jordan Poole        | SG
Omari Spellman      | PF
Alen Smailagic      | PF
Eric Paschall       | PF
Damion Lee          | SG
... (3 rows omitted)

In [60]:
warriors.take(0, 1, 2).select('name')

name
Stephen Curry
Klay Thompson
Draymond Green

In [62]:
warriors.show(3).select('name')

AttributeError: 'NoneType' object has no attribute 'select'

# Ways to Create a Table #

## Creating a Table from Scratch ##

In [63]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'], dtype='<U8')

In [64]:
Table()

In [65]:
southside = Table().with_column('Street name', streets)
southside

Street name
Bancroft
Durant
Channing
Haste

In [66]:
southside.with_column('Blocks from campus', np.arange(4))

Street name | Blocks from campus
Bancroft    | 0
Durant      | 1
Channing    | 2
Haste       | 3

In [67]:
southside

Street name
Bancroft
Durant
Channing
Haste

In [71]:
np.arange(4)

array([0, 1, 2, 3])

In [68]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

Street name | Blocks from campus
Bancroft    | 0
Durant      | 1
Channing    | 2
Haste       | 3

In [70]:
southside = Table().with_columns(
    'Street name', streets,
    'Blocks from campus', np.arange(4)
)
southside

Street name | Blocks from campus
Bancroft    | 0
Durant      | 1
Channing    | 2
Haste       | 3

In [81]:
southside = Table().with_columns(
    'Street name', streets,
    'Blocks from campus', np.arange(4),
    'Time to get there', np.arange(1, 8, 2)
)
southside

Street name | Blocks from campus | Time to get there
Bancroft    | 0                  | 1
Durant      | 1                  | 3
Channing    | 2                  | 5
Haste       | 3                  | 7

In [83]:
southside.select(2, 1, 0)

Time to get there | Blocks from campus | Street name
1                 | 0                  | Bancroft
3                 | 1                  | Durant
5                 | 2                  | Channing
7                 | 3                  | Haste

In [78]:
southside.with_column('City', 'Berkeley')

Street name | Blocks from campus | City
Bancroft    | 0                  | Berkeley
Durant      | 1                  | Berkeley
Channing    | 2                  | Berkeley
Haste       | 3                  | Berkeley

## Reading a Table from a File  ##

In [ ]:
du_bois = Table.read_table('du_bois.csv')
du_bois

In [ ]:
du_bois.column('ACTUAL AVERAGE')

In [ ]:
du_bois.column('FOOD')

## Where Method

In [ ]:
nba.where('salary', are.above(10000000))

In [ ]:
nba.where('salary', are.between(10000000, 20000000))

In [ ]:
nba.where('position', are.containing('G'))

## Print and string formatting